In [2]:
print("Shaikh Ibrahim Mohammed Rashid")

Shaikh Ibrahim Mohammed Rashid


In [5]:
pip install tensorflow


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam, SGD,RMSprop
from tensorflow.keras.initializers import HeNormal,GlorotUniform

In [11]:
pip install scikit-learn

   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.7 MB 3.2 MB/s eta 0:00:03
   ---- ----------------------------------- 1.0/8.7 MB 3.0 MB/s eta 0:00:03
   ------- -------------------------------- 1.6/8.7 MB 2.6 MB/s eta 0:00:03
   --------- ------------------------------ 2.1/8.7 MB 2.5 MB/s eta 0:00:03
   ------------ --------------------------- 2.6/8.7 MB 2.5 MB/s eta 0:00:03
   -------------- ------------------------- 3.1/8.7 MB 2.5 MB/s eta 0:00:03
   --------------- ------------------------ 3.4/8.7 MB 2.4 MB/s eta 0:00:03
   ------------------ --------------------- 3.9/8.7 MB 2.4 MB/s eta 0:00:02
   -------------------- ------------------- 4.5/8.7 MB 2.3 MB/s eta 0:00:02
   --------------------- ------------------ 4.7/8.7 MB 2.3 MB/s eta 0:00:02
   ---------------------- ----------------- 5.0/8.7 MB 2.2 MB/s eta 0:00:02
   ------------------------ --------------- 5.2/8.7 MB 2.2 MB/s eta 0:00:02
   ----------------


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [13]:
X,y = load_iris(return_X_y=True)

In [15]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [16]:
y[:5]

array([0, 0, 0, 0, 0])

In [24]:
scaler = StandardScaler()
X = scaler.fit_transform(X)
y = tf.keras.utils.to_categorical(y,3)

In [25]:
X[:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

In [26]:
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [32]:
print(X.shape)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(150, 4)
(112, 4)
(38, 4)
(112, 3)
(38, 3)


In [51]:
learning_rate = 0.001
batch_size = 16
hidden_layers_config = [64,32]
dropout_rate = 0.3
weight_init = "he_normal"

In [52]:
iteration = X_train / batch_size
len(iteration)
a = 112/16
a

7.0

In [53]:
# ===== Build model function =====
def build_model(hidden_layers, dropout_rate, optimizer_choice, learning_rate, weight_init):
    model = Sequential()
    
    # First hidden layer
    model.add(Dense(hidden_layers[0], activation='relu', 
                    kernel_initializer=weight_init, input_shape=(X_train.shape[1],)))
    if dropout_rate > 0:
        model.add(Dropout(dropout_rate))
    
    # Additional hidden layers
    for units in hidden_layers[1:]:
        model.add(Dense(units, activation='relu', kernel_initializer=weight_init))
        if dropout_rate > 0:
            model.add(Dropout(dropout_rate))
    
    # Output layer
    model.add(Dense(3, activation='softmax', kernel_initializer=weight_init))
    
    # Select optimizer
    if optimizer_choice == "adam":
        optimizer = Adam(learning_rate=learning_rate)
    elif optimizer_choice == "sgd":
        optimizer = SGD(learning_rate=learning_rate, momentum=0.9)
    elif optimizer_choice == "rmsprop":
        optimizer = RMSprop(learning_rate=learning_rate)
    else:
        raise ValueError("Unknown optimizer")
    
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    return model



In [54]:
model = build_model(hidden_layers_config,dropout_rate,optimizer_choice,learning_rate,weight_init)

In [56]:
history = model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=30,verbose=1)

Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5019 - val_accuracy: 0.8684 - val_loss: 0.3270
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7679 - loss: 0.5021 - val_accuracy: 0.8684 - val_loss: 0.3249
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7500 - loss: 0.5214 - val_accuracy: 0.8684 - val_loss: 0.3230
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8036 - loss: 0.5150 - val_accuracy: 0.8684 - val_loss: 0.3216
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7946 - loss: 0.5196 - val_accuracy: 0.8684 - val_loss: 0.3205
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8214 - loss: 0.4787 - val_accuracy: 0.8684 - val_loss: 0.3184
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7143 - loss: 0.5107 - val_accuracy: 0.8684 - val_loss: 0.3169
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8036 - loss: 0.4615 - val_accuracy: 0.8684 - val_loss: 0.3151
